export enum GenerationProvider {
  Artcraft = "artcraft",
  Grok = "grok",
  Fal = "fal",
  FalProxy = "fal_proxy",
  Midjourney = "midjourney",
  Sora = "sora",
  WorldLabs = "world_labs",
  Higgsfield = "higgsfield",
  Krea = "krea",
  Leonardo = "leonardo",
  Magnific = "magnific",
  Openart = "openart",
  Picsart = "picsart",
  Pixverse = "pixverse",
  Runway = "runway",
}
